### ISSUE TITLE
Dependency Pack Download

### ISSUE THREAD

**Issue by Fuzhaojin** [FelixCaae/AlignDETR#1]
Dear Author, Having read your paper, I look forward to using the loss function you have proposed. However, after reading the source code, I find that there seems to be a missing dependency file in the loss function. As follows.
from detrex.layers import box_cxcywh_to_xyxy, generalized_box_iou,box_iou

The author is very much expected to provide the package.
We would like to express our gratitude to you.

**Comment by FelixCaae** [comment]
Sorry for late reply, but I wonder whether you have installed the detrex package? If not, you would install it first.
