### ISSUE TITLE
AlignDETR on H-DETR

### ISSUE THREAD

**Issue by nari95park** [FelixCaae/AlignDETR#3]
Hi,
I read your paper and I think this is a great work! Thanks for your contribution to the community.
I find that there is an ablation study applying your method on H-DETR. Currently there seems to be only the code on DAB-DETR and DINO. Can you also release the code on H-DETR? I would appreciate that very very much.
Thanks a lot!

**Comment by FelixCaae** [comment]
Sorry for late reply, I will release a new version of code soon including H-DETR version
